//
// Created by homerico on 08/09/23.
//

#ifndef TRABALHO_INE5412_PRIORITY_WITH_PREEMPTION_H
#define TRABALHO_INE5412_PRIORITY_WITH_PREEMPTION_H


class priority_with_preemption {

};


#endif //TRABALHO_INE5412_PRIORITY_WITH_PREEMPTION_H
